sudo: required
language: node_js
node_js: 12

notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
  - node_modules

matrix:
  include:
    - os: osx
    - os: windows
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        - choco install python2
        - npm install -g node-gyp
    - os: linux
      dist: bionic
      arch: amd64
      compiler: g++-8
      addons:
        apt:
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - AR=gcc-ar-8
    - os: linux
      dist: bionic
      arch: arm64
      compiler: g++-8
      addons:
        apt:
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - AR=gcc-ar-8

install:
  - npm install

script:
  - npm run prebuild-node
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild-upload; fi
