sudo: required
language: node_js
node_js: 12

notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
  - node_modules

matrix:
  include:
    - os: osx
    - os: windows
    - os: linux
      dist: bionic
      compiler: g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - AR=gcc-ar-8

install:
  - npm install

script:
  - npm run prebuild-node
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild-upload; fi
