sudo: required
language: node_js
os:
  - linux
  - osx
node_js: 12

env:
  - CC=clang CXX=clang++ npm_config_clang=1

notifications:
  email: false

branches:
  only:
    - master
    # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
  - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - npm run update
  - npm install --build-from-source

script:
  - npm run prebuild-node
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild-upload; fi
