sudo: required
language: node_js
node_js: 12
notifications:
  email: false
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - "/^test-\\w+$/"
cache:
  directories:
  - node_modules
matrix:
  include:
  - os: osx
  - os: windows
    env:
    - UPLOAD_POSTFIX=:win
  - os: linux
    dist: bionic
    arch: amd64
    compiler: g++-8
    addons:
      apt:
        packages:
        - g++-8
    env:
    - CC=gcc-8
    - CXX=g++-8
    - AR=gcc-ar-8
  - os: linux
    dist: bionic
    arch: arm64
    compiler: g++-8
    addons:
      apt:
        packages:
        - g++-8
    env:
    - CC=gcc-8
    - CXX=g++-8
    - AR=gcc-ar-8
install:
- npm ci
script:
- npm run prebuild-node
- if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild-upload$UPLOAD_POSTFIX; fi
env:
  global:
    secure: PsU+ejWC7xgJicykVwgkP4h/GYFZ3PIgfbRpa3p6/WZu6aeLSYGzxQSbaXt2cR+hc8Y3O8ZFDTPKYMb3y6cgDHb9RyjfvWnylbibncQuiIYk3f3QidXCAplEs7ePdNabP8vPtX1+bKQ7S7Yw1FB+0b3n1dDMP1FwFKov/OfZfm8497mDAPjp6CzHSATSCGKQPmlnGSrzQnDEY/i2wQzqgpadgsXl0dObXlRAqT5AykjMP/TLXvjbnIbGPCOBUcY8bn4YrXmeokUyXiO7ioGTHHFFkIKg5teTvbx9GW72ID1mKm+HitZlT58YewxsIyu1EgBCtLYBF8L86lr8WceMhcRAacCVp1gQoG5Rp8s/jhaAjUKV011mKIgieuKqN5flY9LVCriTbLou0ubx+c2dy+mfwny1d0P5ofzISOtugwPlP+8TyZ1mFhD7v8N9Af5bXTfdo4XqkqaBKpedrBKdinVEoUbzwJ5dlsI5DQwKfUuF9UQrlNuB6YCZRX7MCcsMMWMPjKpei5+x95JzAmjXt2NVu59L/3Wf8CuHQrwIzoGpZ+klZe4XTCEsIbmg9DN9+55A1pBYUQSZ5RqmmTq4xeBNCxJ9KbzdARHL/UwtR+ZKDuBR46lu5Ldxd/XAXhmygO/AT2H36p9HmiHcl3TPdt2WlXg9CpZmIVW0svuiSJA=
deploy:
  provider: npm
  email: admin@itsrv.tw
  api_key:
    secure: N34WzLPUhH2mY7pxt9MPM5eT1ode4s+JQWTSB5Kr/XF0WGCWGzPMFskRjT/ZBtUNlzZ5SY7lEMp78p2PYMN8xs5JT6z/2D6oU+3dKz7oHY+iAFLm/Y0VYtChCDLHbr5kHSIgXNOALE8lffNUSJG+9Lp3ANVHzA2HJg5LBzzIm4X1N+KxXR0eMZUiJzZ3R8JQ07UrtIXRj/wH7B1qemL4gfsn3ZHonk8zfZAcKnWZyO378GEYIn0tzjnEDEd0BwFeaV09+6GSx9Gpk/Ez6d/HrpSUqyXit3KklyfMH6eOricq+0jjrufz5Rv/IFqtkCKbMCR+fDNceYcy8WoO1guFl1hRs5G3OGw92+1quM5hbU4Gnd7F1KRa4cAhWgDiLeXzAQLz2LcWYKpIqCSZjkEqpBDJ8gtimz9Lp7NfliMnDNih59isoiB854qFmmJBu5ROIjav5g3pRCU/YoL70ExpANYLdYZirEh0/gxytogmcYwIrq+mRUNMJf21QaTigwLfAOmPpl454Z0DQxiN6fvxijJ2ub3lvBHZ7CwaSv7pc1z8bAP71rrjxhjo8vK8DsY3obJ9zUuBLU1rlYOfU7ZOBscvzIoaXI3Qe/P+Dv+6d0O4UFOt2i+9Ynr+RkrsV1srp6bT9BRBFsAKzk5suNh3xJjfBF2UP7sOeyZv4c1xz/c=
  on:
    tags: true
    repo: hans00/fastWS
