sudo: required
language: node_js
node_js: 12

notifications:
  email: false

branches:
  only:
    - master
    # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
  - node_modules

matrix:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
          env:
            - CC=gcc-7 CXX=g++-7

install:
  - npm run update
  - npm install --build-from-source

script:
  - npm run prebuild-node
  - if [[ -n "$TRAVIS_TAG" ]]; then npm run prebuild-upload; fi
