name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Lint check
      run: yarn lint
    - name: Test
      run: yarn test

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.npm_token}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/
    - name: Read changelog
      id: changelog
      run: |
        awk '/^(##|###|####) / {s++} s == 1 {print}' CHANGELOG.md > release_notes.md
        echo "::set-output name=path::release_notes.md"
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: ${{ steps.changelog.outputs.path }}
        draft: true
    - name: Publish to npm
      run: |
        echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
        npm whoami
        yarn install --frozen-lockfile
        yarn publish-all --no-verify-access
