name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: find msbuild path
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.1
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Lint check
      run: yarn lint
    - name: Build source
      run: yarn build
    - name: Test
      run: yarn test
    - name: prebuild arm
      if: matrix.os == 'ubuntu-latest'
      run: yarn pre-build-arm
    - name: Publish prebuild binary
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        yarn pre-build
        yarn pre-build-upload ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.npm_token}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
    - name: Login and publish
      run: |
        echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
        npm whoami
        yarn install --frozen-lockfile
        yarn publish-all --no-verify-access
