name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Lint check
      run: yarn lint
    - name: Test
      run: yarn test

  publish-npm:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.npm_token}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/
    - name: Login and publish
      run: |
        echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
        npm whoami
        yarn install --frozen-lockfile
        yarn publish-all --no-verify-access
