name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Lint check
      run: yarn lint
    - name: Build source
      run: yarn build
    - name: Coverage
      run: yarn coverage
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        coverage-files: coverage/lcov.*.info
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}

