name: Coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  coverage:
    if: |
      !startsWith(github.event.head_commit.message, 'ci') &&
      !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Test & Coverage
      run: yarn coverage
    - name: Codecov
      uses: codecov/codecov-action@v3
