name: dev

on:
  push:
    branches:
      - master
      - releases/**
    tags-ignore:
      - v**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install openssl
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
        export LDFLAGS="-L/usr/local/opt/openssl/lib"
        export CPPFLAGS="-I/usr/local/opt/openssl/include"
    - name: correct msbuild path
      if: matrix.os == 'windows-latest'
      run: npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
    - name: npm install, build, and test
      shell: bash
      run: |
        npm ci
        npm run lint
        npm run test
        npm run prebuild-all
