name: dev

on:
  push:
    branches:
      - master
      - releases/**
    tags-ignore:
      - v**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2016 ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      shell: bash
      run: |
        npm ci
        npm run lint
        npm run test
        npm run prebuild-all
