name: publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, test, and publish
      shell: bash
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npm ci
        npm run lint
        npm run test
        npm run prebuild-all
        npx prebuild --upload-all $GITHUB_TOKEN

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
